services:
  postgres:
    image: postgres:16
    container_name: ecommerce-order-postgres
    environment:
      POSTGRES_DB: ecommerce_order_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: