spring.application.name=ecommerce-order-api
server.port=8081
spring.jpa.hibernate.ddl-auto=none
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml

spring.datasource.url=jdbc:postgresql://localhost:5433/ecommerce_order_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
